import React, { useEffect, useState } from 'react'
import {
  AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid,
  PieChart, Pie, Cell, BarChart, Bar,
} from 'recharts'
import { ShieldAlert, Database, AlertTriangle, BrainCircuit, RefreshCw, Loader2 } from 'lucide-react'
import { getStats, triggerIngest, triggerRetrain } from '../api'
import { StatCard, Panel, Spinner } from '../components/UI'

const SEVERITY_COLORS = {
  critical: '#ef4444',
  high: '#f97316',
  medium: '#eab308',
  low: '#22c55e',
  unknown: '#64748b',
}

const SOURCE_COLORS = ['#3b82f6', '#8b5cf6', '#06b6d4', '#f97316']

export default function Overview() {
  const [stats, setStats] = useState(null)
  const [loading, setLoading] = useState(true)
  const [busy, setBusy] = useState(false)

  const load = () => {
    getStats().then(setStats).finally(() => setLoading(false))
  }

  useEffect(() => {
    load()
    const interval = setInterval(load, 30000)
    return () => clearInterval(interval)
  }, [])

  const handleAction = async (fn) => {
    setBusy(true)
    try {
      await fn()
      setTimeout(load, 1500)
    } finally {
      setTimeout(() => setBusy(false), 1500)
    }
  }

  if (loading) return <Spinner />
  if (!stats) return null

  const severityData = Object.entries(stats.by_severity).map(([name, value]) => ({
    name, value, color: SEVERITY_COLORS[name] || SEVERITY_COLORS.unknown,
  }))

  const sourceData = Object.entries(stats.by_source).map(([name, value], i) => ({
    name, value, color: SOURCE_COLORS[i % SOURCE_COLORS.length],
  }))

  const typeData = Object.entries(stats.by_type).map(([name, value]) => ({ name, value }))

  const criticalCount = stats.by_severity.critical || 0
  const highCount = stats.by_severity.high || 0

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-white">Security Overview</h2>
          <p className="text-slate-400 text-sm mt-1">Real-time threat intelligence aggregated from open-source feeds</p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => handleAction(triggerIngest)}
            disabled={busy}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-accent/15 text-accent text-sm font-medium border border-accent/30 hover:bg-accent/25 transition disabled:opacity-50"
          >
            {busy ? <Loader2 className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4" />}
            Run Ingestion
          </button>
          <button
            onClick={() => handleAction(triggerRetrain)}
            disabled={busy}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-purple-500/15 text-purple-300 text-sm font-medium border border-purple-500/30 hover:bg-purple-500/25 transition disabled:opacity-50"
          >
            <BrainCircuit className="w-4 h-4" />
            Retrain Model
          </button>
        </div>
      </div>

      {/* Stat Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard label="Total Indicators" value={stats.total_indicators.toLocaleString()} icon={Database} accent="accent" sub="Tracked across all sources" />
        <StatCard label="Critical Threats" value={criticalCount} icon={ShieldAlert} accent="severity-critical" sub="Require immediate review" />
        <StatCard label="High Severity" value={highCount} icon={AlertTriangle} accent="severity-high" sub="Elevated risk indicators" />
        <StatCard label="Active Alerts" value={stats.total_alerts} icon={BrainCircuit} accent="purple-400" sub="Generated by AI pipeline" />
      </div>

      {/* Charts Row */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Panel title="Indicator Trend (7 days)" className="lg:col-span-2">
          <ResponsiveContainer width="100%" height={260}>
            <AreaChart data={stats.recent_trend}>
              <defs>
                <linearGradient id="colorTrend" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.4} />
                  <stop offset="95%" stopColor="#3b82f6" stopOpacity={0} />
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
              <XAxis dataKey="date" tick={{ fill: '#64748b', fontSize: 12 }} tickFormatter={(d) => d.slice(5)} axisLine={false} tickLine={false} />
              <YAxis tick={{ fill: '#64748b', fontSize: 12 }} axisLine={false} tickLine={false} />
              <Tooltip contentStyle={{ background: '#161e2e', border: '1px solid #2a3550', borderRadius: 8, fontSize: 12 }} />
              <Area type="monotone" dataKey="count" stroke="#3b82f6" strokeWidth={2} fill="url(#colorTrend)" />
            </AreaChart>
          </ResponsiveContainer>
        </Panel>

        <Panel title="Severity Distribution">
          <ResponsiveContainer width="100%" height={260}>
            <PieChart>
              <Pie data={severityData} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={55} outerRadius={85} paddingAngle={3}>
                {severityData.map((entry, i) => (
                  <Cell key={i} fill={entry.color} stroke="none" />
                ))}
              </Pie>
              <Tooltip contentStyle={{ background: '#161e2e', border: '1px solid #2a3550', borderRadius: 8, fontSize: 12 }} />
            </PieChart>
          </ResponsiveContainer>
          <div className="flex flex-wrap gap-3 justify-center mt-2">
            {severityData.map((d) => (
              <div key={d.name} className="flex items-center gap-1.5 text-xs text-slate-400">
                <span className="w-2 h-2 rounded-full" style={{ background: d.color }} />
                {d.name} ({d.value})
              </div>
            ))}
          </div>
        </Panel>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Panel title="Indicators by Source">
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={sourceData} layout="vertical" margin={{ left: 20 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" horizontal={false} />
              <XAxis type="number" tick={{ fill: '#64748b', fontSize: 12 }} axisLine={false} tickLine={false} />
              <YAxis dataKey="name" type="category" tick={{ fill: '#94a3b8', fontSize: 12 }} axisLine={false} tickLine={false} width={90} />
              <Tooltip contentStyle={{ background: '#161e2e', border: '1px solid #2a3550', borderRadius: 8, fontSize: 12 }} />
              <Bar dataKey="value" radius={[0, 6, 6, 0]}>
                {sourceData.map((entry, i) => <Cell key={i} fill={entry.color} />)}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </Panel>

        <Panel title="Indicator Types">
          <ResponsiveContainer width="100%" height={220}>
            <BarChart data={typeData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
              <XAxis dataKey="name" tick={{ fill: '#94a3b8', fontSize: 12 }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fill: '#64748b', fontSize: 12 }} axisLine={false} tickLine={false} />
              <Tooltip contentStyle={{ background: '#161e2e', border: '1px solid #2a3550', borderRadius: 8, fontSize: 12 }} />
              <Bar dataKey="value" fill="#06b6d4" radius={[6, 6, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </Panel>
      </div>
    </div>
  )
}
